//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelGalaxy
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalService
    {
        public int ID_AdditionalService { get; set; }
        public string Название { get; set; }
        public decimal Цена { get; set; }
    }
}
