//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelGalaxy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agreement
    {
        public int ID_Agreement { get; set; }
        public Nullable<int> Бронирование { get; set; }
        public Nullable<System.DateTime> Дата_заключения { get; set; }
        public Nullable<int> Список_услуг { get; set; }
        public Nullable<decimal> Общая_стоимость { get; set; }
    }
}
